In [1]:
import torch

In [13]:
tes1 = torch.tensor((3.8,5.4,8.3), dtype=torch.float16, requires_grad=True ,device="cuda")

In [14]:
tes1

tensor([3.8008, 5.3984, 8.2969], device='cuda:0', dtype=torch.float16,
       requires_grad=True)

In [31]:
tes1 = torch.tensor([[2,5,7],[4,6,8]])
tes2 = torch.tensor([[1,6,9],[2,3,4],[6,7,8]])

tes3 = torch.matmul(tes1,tes2)

In [32]:
tes3

tensor([[ 54,  76,  94],
        [ 64,  98, 124]])

In [34]:
torch.mean(tes3, dtype=torch.float32)

tensor(85.)

In [40]:
x = torch.arange(1, 100 , step=10)

In [46]:
x.argmin()

tensor(0)

In [53]:
x = torch.arange(1,10)
x.shape
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
x.reshape(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
x.view(2,3)

RuntimeError: shape '[2, 3]' is invalid for input of size 9